apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-vpn
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: qbittorrent-vpn-secret
    template:
      data:
        VPN_PORT_FORWARDING_USERNAME: "{{ .username }}"
        VPN_PORT_FORWARDING_PASSWORD: "{{ .password }}"
        PIA_PF_GATEWAY: "{{ .QBITTORRENT_PIA_PF_GATEWAY_CA_ONTARIO }}"
        PIA_PF_HOSTNAME: "{{ .QBITTORRENT_PIA_PF_HOSTNAME_CA_ONTARIO }}"
  dataFrom:
    - extract:
        key: pia
