---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-pia-wg-ca-ontario
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: qbittorrent-pia-wg-ca-ontario-secret
    template:
      engineVersion: v2
      data:
        wg0.conf: "{{ .wg0_conf }}"
  data:
    - secretKey: wg0_conf
      remoteRef:
        key: pia
        property: QBITTORRENT_WG0_CONF_CA_ONTARIO
