apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-vpn
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: qbittorrent-vpn-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        PIA_USERNAME: "{{ .username }}"
        PIA_PASSWORD: "{{ .password }}"
  dataFrom:
    - extract:
        key: pia
