apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-vpn
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: qbittorrent-vpn-secret
    template:
      data:
        OPENVPN_USER: "{{ .username }}"
        OPENVPN_PASSWORD: "{{ .password }}"
  dataFrom:
    - extract:
        key: pia
