apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret-vpn.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
configMapGenerator:
  - name: qbittorrent-scripts
    files:
      - port-sync.sh=./resources/port-sync.sh
      - pia-port-forward.sh=./resources/pia-port-forward.sh
      - pia-ca.rsa.4096.crt=./resources/pia-ca.rsa.4096.crt
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
