---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sabnzbd-pia-wg-ny
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sabnzbd-pia-wg-ny-secret
    template:
      data:
        wg0.conf: "{{ .wg0_conf }}"
  data:
    - secretKey: wg0_conf
      remoteRef:
        key: pia
        property: WG0_CONF_NY
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sabnzbd-pia-wg-dc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sabnzbd-pia-wg-dc-secret
    template:
      data:
        wg0.conf: "{{ .wg0_conf }}"
  data:
    - secretKey: wg0_conf
      remoteRef:
        key: pia
        property: WG0_CONF_DC
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sabnzbd-pia-wg-va
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sabnzbd-pia-wg-va-secret
    template:
      engineVersion: v2
      data:
        wg0.conf: "{{ .WG0_CONF_VA }}"
  data:
    - secretKey: WG0_CONF_VA
      remoteRef:
        key: pia
        property: WG0_CONF_VA
