apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-assistant
spec:
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: multus
      namespace: kube-system
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: home-assistant
  path: ./kubernetes/apps/default/home-assistant/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: home-assistant
      VOLSYNC_CAPACITY: 10Gi
