apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ""
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3N0hFVWhVbWx1OHp6RStO
        d3F4aXZWdFFIR1N3MTZLeHFHME1XZmFhU1Y0Cnc0OTVsajY1OU1kTHdPV1MvRzdk
        SGpHbXRNemlYeW9ueFFNRENyYzgveHcKLS0tIDlFekJPVmp5ZEd6b01qckQ3cnRL
        dUZ4MXRYYkp2RXBLZmthVHI5ZEFWc00KHuv2mpQMsCwdC0wsRBl/uYan5Oz5BqnZ
        say65kM7MNBZhEZIajuPhfr0GDbX0+KkRVE8sfSEvdZ2Wv5rZ5QWNg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j4urt0rxfl0hnenrkqakvryzy6uuhaugjkxtu3jemzd7rv2lzy0sz90gze
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-20T19:46:35Z"
  mac: ENC[AES256_GCM,data:sgYv0uEtRIvOvhD+vj/cD7tA93wocaHQnMixAl5/korDR3SqEZQVRepw4iI3HxH6EsWkDdgBEPQ5m6T+mlWiCe3rZK+wYrgbvjQBW9O4frhTEn1ZbaH+KvLoNGRjK6IaOQL+er9IwRs1694Of4VEpYwnxDY8Wx0yYu+6GkzWPyo=,iv:PObpDJCcrd9EnoSQRmX4lVx3AoTFsPN/WGeBFL92pTQ=,tag:WBuDQwOk0OOXYzM0+zdnqA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
