apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ""
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlajNsMnAvbzFoOU9mbjJi
        YkZsOHFzMGorVjdSdWQ5RkFGZkEyWGJJOW5JCnErYjNoSDE1OWl3MjJNWEFIc2VI
        TVBYR3lBbWVhbnp0Z1p4S1h2VnYrM2MKLS0tIEY3M0hUM1RydFJTSGVGbXVYUnZo
        RDVWR1RIaHJqR1pzblBiUHBtck5CVGcKobXp2d2bDnf40ySEmmLoS/uFa4xygI+h
        DQXSqfxJYnRj+hfTtLEDgriDgFLKOLyh9tWSGK/6OQld4wD/mfY29w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j4urt0rxfl0hnenrkqakvryzy6uuhaugjkxtu3jemzd7rv2lzy0sz90gze
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-20T19:03:08Z"
  mac: ENC[AES256_GCM,data:VPFckopLcG+NVl1Gs7iyjOXHIDtbjv0gsouc3ewTsXlDEbhx3J3+Kevej0XQq8Jq0f/YqOxshUv1dvyL4VDtau7PoNYYES8d5YFiQKn77Yz+JznveeYGnaCzS/Gn/VdfB0CFwCsKpOZ9ESPvLctLdT9QP4OfD166sGXFVQ0MruA=,iv:vevZeBB12XfSRLt6cd4GM+e9I1lzzseVHS4lCz8OfQo=,tag:5C+XD5O/9R/JoPqasiQY2g==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
