apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:6ADnoURLG8HzmJJtMGtostmZjXkYN6ZV8UrD3MP9RUOSXPMY+Cx1oQ==,iv:tyLVc2Ocmvqr1kSSJ26paA9DdQciDVp19hDQabT/jdA=,tag:YWJkqPyEDpGwQdoON65SLA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVjR4ZkZKNnp3Q1pDNzBi
        eWxweGUveGJZakZ5QnRDdkVtcTZBb0xzamlVCnZ1N04xWVN0NHZPVkJpRmhaRity
        dUZ5SmRqQm4xb2pyaDdmTXBnQnZrdjQKLS0tIExwWlQyYlZJU3FORWk4eGVrOGh6
        dURmUC9scFpvWXl1aXpBMWNablFLVDQKBSSQnAYEsCQkUasYWzDRbxjYhSxP0y7J
        cap5cbltYMej+cSHr1fFUNhOK5a6hEjoGOykWe+E3F1DwQn5Z3XS6g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j4urt0rxfl0hnenrkqakvryzy6uuhaugjkxtu3jemzd7rv2lzy0sz90gze
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-20T21:34:12Z"
  mac: ENC[AES256_GCM,data:G85lFNPo8XAbzGdZ5ey0BxnpUyYsKzapWklJ3wjLeGp63+YgZKnYh75puBVvLUrS12PzxdcCCAGVCD7Kirb0McbK9J9Xc0gov4+li8AbMaKPfhPuX3kQEQ7RQ3ypc7dtQQ0GguXChG0i7PjzSyRQfiCqDZiaRTrumECKHBi6Lbs=,iv:2+cetapU1sP+xiv7Pa5GFdvxmn21dxYU+4eFbEkfwN8=,tag:+q29Y8LRARcbzNKSo0KDgQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
