---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-volsync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ${APP}-volsync-secret
    template:
      data:
        KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD }}"
        KOPIA_REPOSITORY: filesystem:///mnt/repository
  data:
    - secretKey: KOPIA_PASSWORD
      remoteRef:
        key: ${VOLSYNC_SECRET_KEY:=${APP}}
        property: ${VOLSYNC_SECRET_PROPERTY}
