apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ajLckTGTRg926fohrg==,iv:UY0bXJtWyn7seqSxb1BfP3g8KC8xeS0lbmssi/WTWtk=,tag:yNuPPZYcsZ28ZXUWPdJUNg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMmhuei9HS2c3OHJGQTVE
        OHppYWk2ZkdTT2dEKzFRT01mR0kyenJGMFFJCll6a3RTRjJ0cHhLbXVFUng5eVRZ
        Rk9wZXBEUGdzQjZGbjJPbnNuRHdSZ28KLS0tIE9lOFZqRlB4ay9oUjFMNmFtQitq
        c3phbGE1bThUNms4WUlXYVViRVo5WjAKxSTFjpiYGAgW1LCN/YUsGFrDfxLEOVMo
        5fWER5mFdZTtm2IRWj2Zm2ltMTxkTyqX7OeF8+YZCjFW0Kd14sOHNw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j4urt0rxfl0hnenrkqakvryzy6uuhaugjkxtu3jemzd7rv2lzy0sz90gze
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-20T19:03:08Z"
  mac: ENC[AES256_GCM,data:hbxS2wa4BS2d4oa0q3wM+SeyR3jz5KNTF7JA9ikRfLenkSQo53KEe9In7jOsOe19ObY3OhqMV0wQqYSOMJl66GCbhTjLLPeS98tSYqqfVTp4PYvZMjzJ0ssTq+xiKC30W3vprgqrK8coyls7j/4c1sMM2afBe5GbLRNwHFUSSUY=,iv:t1bwkXSOzaor6ai++4RIdKvWG849wzUxTyDi6jX9xYE=,tag:FzzytPziWZ+lhjXVwdxhIA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
