apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:OJJjP3j9BgLSYiUeJg==,iv:xLSrKi+5Ou+y/MsJVj2jihsK6dKQ1NpGh9/YcznRn/o=,tag:IINd1kfRXaZ8qlQM80Vgdg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBac2FyVDVUcFpiM3VTUTNq
        dGFyd0hOVlFEZE5odXZLNlZCRzA5UEpLY0VrCkw1WGJMcEllU1NFWXNUNHdkS2tH
        eDlFWW1WZ1oyZ2ZMYWc3TWRHWWdXMkUKLS0tIHZ2anRjWVhDNnIrSFB1SGRnQkg3
        RVY0NUUyaTdxT2tpd2FJSHNzVGE5ODAKBePzh138NBzf1m0P/Sg9R9TzyKLcfaio
        TTJt1BdiNQ/VSLHsj4UtOvyaNnON4KmbZn3x8e8NNZqUpTUtCnlDGw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j4urt0rxfl0hnenrkqakvryzy6uuhaugjkxtu3jemzd7rv2lzy0sz90gze
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-20T19:46:34Z"
  mac: ENC[AES256_GCM,data:8Cnxj8RF3Qp8E9c9Wtd3VyU9xp9MOYPC8AO2q9wf2kDiPUiRyYkT7rsd3ebeoGF6ZEaWDu7RbBFTT/wSeyypmhIazyjEt/pbKVsUXHlF4Sr0p2nlBUNwTQUHfhi/8/RCGbkUXnDoaeIyGovc4vXi40fGahmDwv+FUlXHamJ6IkY=,iv:jyAQf5IbCGgCkWjfzJvdSrwWxP0J77CGCq6P+rNEjjM=,tag:HQeSlJBp0y0CcKwQ+4LYnA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
