apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:FCgaA83chGsWtnmalg==,iv:sx951Li69RAxWjyCrAa3ZSZQKj23kk3fjH4f6233Y/M=,tag:cT9/34L/DYpGNd3nKb+p0g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMEdJOWVzUFNaN3E1STlJ
        NEpVMG90YzBZVGd3N2lJQzRkOUlNaC9uUlNjCmJUSk1wUFVUN2VldjBQY1ZVa1g0
        S3Z6M0phRFRsMUtBRkhMTTRLaGlyd0EKLS0tIFpaNXh1dG5VM2ZPeGxpMm9XVlNy
        VlIwaDFSdFkzcmZRWWlQM0tRNDhoTDgKjpzAu6e1DSPQC5u87F/VThOIk+Vel9IC
        ndbPl+M6kgIhqPcK4nQyurBPHncWlAMpYS6kiJgIneih37dnDb8y0Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j4urt0rxfl0hnenrkqakvryzy6uuhaugjkxtu3jemzd7rv2lzy0sz90gze
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-20T21:34:12Z"
  mac: ENC[AES256_GCM,data:SAB1y0wBEizoWYqGnoYkGVEv5hGKLIH8qpWjik6gUyN/YjF6+o/UJ0ah4aWe2kEqveV64VFK3wQzMW4QISDGDTIh1F/L+cveqfIj8aSrvYJEts6dVHhVaVfx6UGtLUj8YAnltTCP3hpbPahjVxLkHWXHcBOnRpbpRRSXdy2igFU=,iv:QnIbAczoA4/hTzmfg+3zrgHhZAldxFhOBk8qFrXmDTM=,tag:LEjnM9+e6nL1SFBSJVZ4fw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
