apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:di4TjcEQUvB96ToC2SU+ziKIw4/A2BumQ+JUrmqGY9Q=,iv:urdm7OiR85TWS8xNv4ghogwXutsyzSMkow/sMq/3VdU=,tag:o8H5pUT1mIDdA7RsIDXJmQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZ2xLbC9xV3cvSjRCLzFW
        dUNRVm9yYXMvTTVUY2RnK05kV0VCN1A1Y2c4CkswUnFiQWdRNnFIVEp6L0YrdEph
        OXhmWlVadkkyekJ2WUdRMnZHd0lmM2sKLS0tIHpleDl4eDIyczVXSmJidWJvVVI2
        MDNJVWJzYU5jS3BteDBYVzFObms4bmcKnY6Ke2d+yUfUgD2VR45TTZ8CTY7+jb15
        boRlz2NyrWJ6ZENgAaLVjyS/SPk+hUFsAQ/ZUk9ZG97YtcAB3qUGyw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j4urt0rxfl0hnenrkqakvryzy6uuhaugjkxtu3jemzd7rv2lzy0sz90gze
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-20T19:46:35Z"
  mac: ENC[AES256_GCM,data:WtZfVeYMRM5R0OHkXXFkdmYXgy12qIwpmSwVqvOvOc3GGJOn83PlvxYN5ae1ZDgiJxyzfnpwKx/rU3281ZF8UacfQbKnLnF+JAQPOZ4b+be0D25pGf503G42Y37n0gKEWpXY3ztddGkSh8uRmF06d25Eazmdwp14ODbIjzuAqo8=,iv:QQ1UGUcQClOuV9bzz+HQaZmrVSAtv3Wboeo33ZoL3WI=,tag:HvRq8GHe7jf2NZarxDT4lw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
