apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:k/zWBxvPwfB67FTeqW+PvBxzrrFb2zW1Oov8mLfFnbs=,iv:LbLS1ANqqtDmD9aWIYav02dn3YNSe7crQcywkRnk/AY=,tag:H45+D6yVAeZP50WbBIUINA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVUczazByZFllNncvKy9L
        M3g5ZjF1UWxyNVBlY0NXeEt5WmM2M3A1NkM4CjM0alR1c2h6MWVRVnNkdlA0M0Vs
        K0pYRlRTNmloRjV0V09XQmx2b2NXVzgKLS0tIGpCWVNwYW0rTlp1NGlFdVdGZ3h6
        QUF1TnpiQkdFV01xb1g0NCtQYVhrWEEKFrUsyErmkQL2Mm09ThX96dDUsg/p0hVj
        0pVDB1xIscq4Duxysz9rzD7APOAth6RrB+oeMxx2Ib8OvADySA7Xow==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j4urt0rxfl0hnenrkqakvryzy6uuhaugjkxtu3jemzd7rv2lzy0sz90gze
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-20T21:34:12Z"
  mac: ENC[AES256_GCM,data:eJ/VWaXaa2MqsCXlay4wDS1et1/1Ap8zjkUVbYWl4rewCSVyHkbSyz4zpTsW6kc8hXU2+Zkng1lNE8lWjHtVX4qsXhSHndO2zwEkxLHO/yaFU1dJouLTZmPM/lM0o1xycJw2dzqviVNSQfwQeMaAWvx9AbF+nPDBUBwz8WLT74A=,iv:gEX69+Wu+XS2fFCPBjv/LtUUScAbUBQEVL49V8Dk2O8=,tag:n+LjLeIxFT5X6Ngr99rVbw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
