apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:GAigt+aFqnoQT6kRGIofBHrd9N0/XVLaJniGqs1YDgw=,iv:P8KJlGV99zgZvJX233cmZNxUZIwDfGqhGfFVLzkdj+k=,tag:ahyTF+WwlTS1U29LF8TCxA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiR0pwalN4cjNMNDVRTmV0
        NU55MEloTWdsWC9aaXZmeWNFb1RCYXl0R2tvCkJ1NVk4SGx2NTBXRXZuRTZoT1p0
        R0hlWUhEamo0TGxWZ0JtcnhHVWpzUkEKLS0tIGtXcjFxTG5FcWgzSkwvb2dRUE1x
        a1o3clhWTVZhcjc4SEN5SnJkLzRvM0UK1JdToA+qQeDtwv8MJSQ2HmfnJiCtC60E
        xJ0yijqBu9Vbw7bglrOOQVCswCC75xVB5KtGDeeBzRaEPNid51KLDw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j4urt0rxfl0hnenrkqakvryzy6uuhaugjkxtu3jemzd7rv2lzy0sz90gze
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-20T19:03:08Z"
  mac: ENC[AES256_GCM,data:rE+pcTX9nPAo/BW4e2IiUxcWeHaACxQYTl921HHwRhLXWD8Z1L17dY36I4ojG9h9EfReJOiCcuvTZkGPvz3fxbE9+dElmn+2CxFMgrqSe/u++hft/GX5tCmR63xV/bi58zCzkbACUmeBfBPL02zhe+iCxijVNw+ZNVLnuhMk8TU=,iv:LMiNqwxpBLScuUVqPieHp0CDIJsm5EhipVoIlCzEnnQ=,tag:3LPjG5icFmVM3zwYA6c7yw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
