---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stash-media
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  mountOptions:
    - nfsvers=4.2
    - nosharecache
  nfs:
    path: /mnt/bytebarn/media/adult
    server: storage.cooney.site
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash-media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: stash-media
