---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cluster-secrets
  data:
    - secretKey: INTERNAL_DOMAIN
      remoteRef:
        key: home-ops-bootstrap
        property: INTERNAL_DOMAIN
    - secretKey: EXTERNAL_DOMAIN
      remoteRef:
        key: home-ops-bootstrap
        property: EXTERNAL_DOMAIN
    - secretKey: CLOUDFLARE_TUNNEL_ID
      remoteRef:
        key: cloudflare
        property: CLOUDFLARE_TUNNEL_ID
