apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:GCBwfQHmD/DmFTIe62YpUm3Qk3it3wMq+cT20+AkvZ3jI8gX+BpevLkfHJ/jH64BoypS9RJ9KSY1LuKuJy3y75LojS5g9SlhGQCxBTKL4/0SG4AGyfgrMDevYW3qjsJMmKGudtsZNw/HOaDrbF6fTprvSkM1iJabtOI2yFE+HHAByOEKGzbMd4LB5Fu0qbImIpo3VvINNmq1OHSSEe6NXDDAJL+5+QiTGYTzE+a7LT5EaCbt,iv:0HSP69K9msN5dI3WiRy89X67MAzQfKWCPHhOIkttmBs=,tag:nQM1ijV87nGijp/EUt6Gww==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtK2djL2w3ak5Gb2t5ay8v
        aURwRkFlZnMxbDU4bnB3VmFvM2RUTVRVWmwwCkN2aG9iVWlaenV2Q2hqR3NFMUJC
        V2kyQmRuK3FnYzU0eFR2ZUlsaGJLaWsKLS0tICttKy8xNm9QcWZLYVhYM3NTem5C
        QlY0QWx5SktSbmZ2dnNyTDFYYnNzQ3cKbr8DfP4PCIWQJavCDk9tYolK64ccP43N
        JCNyZQGCQ9eehLbz/VleppWWRUR84HPTxrM8LfuxjQg25mAHMmn6Qw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j4urt0rxfl0hnenrkqakvryzy6uuhaugjkxtu3jemzd7rv2lzy0sz90gze
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-20T19:03:08Z"
  mac: ENC[AES256_GCM,data:bJnBhb4DGQM5E7W/mwnjARPWhsHBape2nQjSpFZDtJPU63y2WuXJFH7DQKOq57pEcJIWLuuh0NLQaDmL64si4YscxrXfCTMeVC1Y48N7jBaVi+BjEHhKI8BMWBr6sc5c8PQtR4kSWUYjrrZdCCukAO4yo6ywcetZrco+F7QV+B4=,iv:tr/W9PVvcxD5ni8zYCedEFPCmm/rtS7N0Ye1jcgQP4g=,tag:tHoJn/BZ0Rg1xjxKklsjgw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
