apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:sn8EJZKlTNZ5Cq17GVtyP01ImVDA1WOwubOb7ArqV9iDsKFYOzJyRuLqHrp8hG7d0lKjCypHNw8w8RGpVh9oNFO1Ug8Xev1z8c+tec3xcUL4KXYoIQppehxRTMIBOh4fQTgCEF2rv88vF67MJzrZ/OXISIE8ucZGdJ+gzHGuSIalAFbLPDwbrPOKzYRrwqTgu0OwG03JrF51cet1nwrSOhgT7cJqvdMNDkS7qs/sgYNDrrAg,iv:8fgntSd0g0/dymLKVDh6KJ0jGfJr0c8SQxQFK7wLs+w=,tag:DOnQG+Tz6yBfcsAHfX9miw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3WkxQWlYwZFhjK2FEU3Nl
        TWlwNnVyTTgrdTR5dHpHa0dLckp6SVY2L2ljCkthSmlySldJQnZlSzVjSWhwVVR6
        MkNRZGVDNlhJK0lIYUVIMjFSaU1SQ3MKLS0tIHltNkJnWkFDOXFXTEVmVDEzRjJr
        TG1pK1U0UVQrL0huUVFUamM4T3RjRWsKSP4c3RTIKaB80C4Rf7v1XIuo7QccIJSr
        tfufWNzOm+5MHrVkcbuXwd/fW8ZWhluf0gxrZP82nmBM1rwSuynFDQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j4urt0rxfl0hnenrkqakvryzy6uuhaugjkxtu3jemzd7rv2lzy0sz90gze
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-20T21:34:12Z"
  mac: ENC[AES256_GCM,data:PBbAtoYHQT7/KacLpwwidjc1xzRf5HWDNshbF+VHGFjuxVlKL8Ri0UFwP/UZ3Zl8zu0yDvGIbRklki1Sgmu6aWggaBQIjepkd2mDiuRHKddc0aqUWskZr1tHMtwUHA0GAee1KByCyul7jAi2I5LR9yK322/89NFrTr53fuJahbs=,iv:pJ+R8c7ApY19kuKoyFQBiZ2cE8F0IZncIpeByivNSRs=,tag:tpUwlIt767YxgzkadtdiFw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
