apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:wJRdBuge2wHYuSUFryAkTwStpwgGsnWNFXI0SRjX8IgqMbNHpMF30l78nFqx+5vv/z9qbP39tX9mhx/L1B4cj1Pe91Ox6A2c1y5NegnC7Os3DKfCRXtcrHHTN0oOY/OclEYHKCxirFtKFBrCsIOHwYaGX1F2XRjjFWSg5bcpss9yWm00T3IAFwvKNsG3ijKzjb2ybpnYiSi4smiyRgQt2Ibz9eougoWHnSN/TfReitF4tO1E,iv:1NZLQUhQJyoyWdz9AODV4fs5cZ8Lv5VfVSuaN1V4wAA=,tag:sBmRemgxcB3uscWV8E0vAw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSK0pCdEIra3U4VnNpQWhy
        VzlmM3k5d3RQSFpTSHkvS0xuTjRXeWRUWVR3CjRoODFteDF4M1V0RWZrMW5Sc25Q
        Q0NTNXlKemllK2tkRmRTMHU2U0M1WGcKLS0tIFVTV250Q2lxQmVZbkEvTGpOa1M4
        U2hiM016Q1FoQ0dRVUtua1lWMzkyWGMKkEgBQKW7J1omMz8rYWHwgU7RVQgWUrov
        0Pza7T34PdvhJvOX9ZnpyDskWdCMGXybBAAQyYmwWNbFRrny7iTlYg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j4urt0rxfl0hnenrkqakvryzy6uuhaugjkxtu3jemzd7rv2lzy0sz90gze
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-20T19:46:35Z"
  mac: ENC[AES256_GCM,data:26P9D/WzuuZDenAZ2GPC77C4mmN6gtg5bsbmk97/tIQnKR0Tz+ZwGygMbcJVQN64Fn5DNSs8o7I7sGQJcqnv/cYGgVf+MwFWkvPNAftX5wKyg+xlCy50lulZe32Nd1y4+J2j0NPUSe4/uzbwGDsSv7zpCyKaRuhhhtrkEU14pxw=,iv:ujEGDRBUwSFj3C+WNokFLWOatDuK24pc1SI4nliXBD0=,tag:86dVPDk+tLqtOBSNNpizKA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
