---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cert-manager-secret
  data:
    - secretKey: api-token
      remoteRef:
        key: kubernetes/cloudflare
        property: CLOUDFLARE_API_TOKEN
