apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:DSx8VFDDM/1rDmIA41Itza+B/trEsQE6z6e7YQDXQ4Sp4aUsg9jnRw==,iv:mMPSE/QhLcquyvFNkk5XBRzJScCHH9qh83W+Vn7nwus=,tag:JuooHpG0ooqpMTV3DNLeJg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UUo0Yzh4ZHVyejgzR0U5
        a054blhJbEt6U2diRTU5bDN4Z0taYWp2YUFVCnpJTkR4OFMyWERnVEdZTVZIUXlB
        bVBKMnEyVjY2eWZiVUwvdW1YS1Vyd1kKLS0tIDFleHEyWU40L3hUaHpNd29QVGo2
        K0NxQmgxcDJzUDdwdnZraEFjOUJGK2cKlncrdRvUgrCvN9dAa6c2dwufVrsBBrX9
        Z1DuHg/kIAPgb4mfYNSszaw7JQfllCkEVTfR8dZYwvYpY8c893PSow==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j4urt0rxfl0hnenrkqakvryzy6uuhaugjkxtu3jemzd7rv2lzy0sz90gze
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-20T21:34:12Z"
  mac: ENC[AES256_GCM,data:9dToErQp0AeWLz4dA/atqw0FP3Y12odHj2JKMRsfBcTjXYMYvIF0hNfg4uPKq+Z1VvbQNwxnnYnfxP/c+d9dn64abzMm/Rbw70py7NVbUGz8g2DM96C+HbgaxKLFZsMmMX33XLeYLQ7zg7Hh8i8rfohteRi8ScjS2ckQIrI4Og0=,iv:VhSeUmgJZsihkNnla1G/w/mdIc1d3qjp4ORJAyIi6D8=,tag:fczyR1tIawdXlW5YxaqjmA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
