apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ""
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSL2ZjOUxPN0hzQms2Yk1H
        T0RCbG13L2hORlFkZGYzK2haSmRaM1NwVFVJCjQrYk1OQVJtY1ZZVk9JT3N4VjVt
        QWszWWF0YTE1ckdnbzRNdFIyZWV0emsKLS0tIHNGSS9IamJFdW4zUStKOGRjZ0FH
        MHFZMWlKZkU1NjM3Z0hzaU14cFBROGMKY46G9MHT/iJIk/wSxacqaobjy8GLXz5/
        u+T8YxfG1VO9PVauVBFR26L+udsLepwxVIqjV/L96wJRwNXlBjm6vg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j4urt0rxfl0hnenrkqakvryzy6uuhaugjkxtu3jemzd7rv2lzy0sz90gze
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-20T19:03:08Z"
  mac: ENC[AES256_GCM,data:frr5qhkrbvUCybUaE/5OrXibr1OtMk3jdUtfuMIGKB7V6RNiv/N+3Du1dSl5Jr1NIMRLoQPTdHe9rX9hCgXDBIA4z9YqEJJH9Az3cyNU4lIV8zdkWrkTy1wizP6SRhOvwLKj2MboXF9WGRtH01jgZZ3g1GXTS5xh/nLFwlsBiD8=,iv:u/P4HrcW+rD5nB75HgsqpxUPPSk0fkmFFxEtcv3sRmc=,tag:SoKnY95CQWp74ojRAfG42Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
