apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ""
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNHArWktWdE5DM3FweVJY
        MlRDbmRPZFpWM3l5akFNMXVYYWl0a2UrNm5nCmpOd1Q3WWNtWHRrYm1iK1Ztc2lX
        eUNBSUJ0dHVMdmhBTE9GWjg5SEMxWVkKLS0tIC9sdTJaSFBpRHJGNk1Gbk5haE4r
        eXY5cU5qR0Q4MU9JUkh1eUI2SFBpa1EKen5CsKjvHEPpvWnhAtHZ5N4tq/aH7zIf
        Lfb4xtDshAtBtlORJFK/W6dyD9/MQIJaeTdKGcGwvHyVFVBLEjrcnw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j4urt0rxfl0hnenrkqakvryzy6uuhaugjkxtu3jemzd7rv2lzy0sz90gze
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-20T19:46:35Z"
  mac: ENC[AES256_GCM,data:/bhCPd8CRSE+48uCg/Qxmrhrlzqyoi1/qgG/mLsuYPb4ScmCuremMmfA9A07GWuSbKfu5EnZ7GlrWnlu8cerDAm0X9xlUXl5dI3hHxcBTluA6k9QaJKuO3YRGahfs3cPWA7gVYDgyI5kNMnD65kPcEDqttVVZZuBUunbxbC/9CU=,iv:AXWCPVC3lViwMQjj+nHXm5NmAH+otXQ5kknqMsX9VDg=,tag:3OW4KwSqynM1jaaIFG6fjA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
