---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${EXTERNAL_DOMAIN/./-}-production"
spec:
  dnsNames:
    - "${EXTERNAL_DOMAIN}"
    - "*.${EXTERNAL_DOMAIN}"
  duration: 160h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
  secretName: "${EXTERNAL_DOMAIN/./-}-production-tls"
  usages:
    - digital signature
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${INTERNAL_DOMAIN/./-}-production"
spec:
  dnsNames:
    - "${INTERNAL_DOMAIN}"
    - "*.${INTERNAL_DOMAIN}"
  duration: 160h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
  secretName: "${INTERNAL_DOMAIN/./-}-production-tls"
  usages:
    - digital signature
