---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN/./-}-production"
spec:
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
  duration: 160h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
  secretName: "${SECRET_DOMAIN/./-}-production-tls"
  usages:
    - digital signature
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cooney-site-production
spec:
  dnsNames:
    - cooney.site
    - "*.cooney.site"
  duration: 160h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
  secretName: cooney-site-production-tls
  usages:
    - digital signature
