---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: snmp-exporter
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: snmp-exporter-secret
    template:
      data:
        SNMP_COMMUNITY: "{{ .SNMP_COMMUNITY }}"
  dataFrom:
    - extract:
        key: snmp-exporter

---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: snmp-exporter-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: snmp-exporter-auth
    template:
      data:
        auth.yml: |
          auths:
            home_v2:
              version: 2
              community: ${SNMP_COMMUNITY}
  dataFrom:
    - extract:
        key: snmp-exporter
