---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atuin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: atuin-secret
    template:
      data:
        ATUIN_DB_URI: "{{ .ATUIN_DB_URI }}"
  dataFrom:
    - extract:
        key: atuin
