---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
spec:
  chartRef:
    kind: OCIRepository
    name: postgres
  interval: 1h
  values:
    controllers:
      postgres:
        type: statefulset
        containers:
          app:
            image:
              repository: public.ecr.aws/docker/library/postgres
              tag: 15
            env:
              TZ: America/New_York
              PGDATA: /var/lib/postgresql/data
            envFrom:
              - secretRef:
                  name: postgres-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              allowPrivilegeEscalation: true
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 2Gi
        statefulset:
          volumeClaimTemplates: []
    defaultPodOptions:
      securityContext:
        fsGroup: 999
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          postgres:
            port: 5432
    persistence:
      data:
        existingClaim: postgres
        globalMounts:
          - path: /var/lib/postgresql/data
