---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: home-assistant-secret
    template:
      engineVersion: v2
      data:
        HASS_LATITUDE: "{{ .HASS_LATITUDE }}"
        HASS_LONGITUDE: "{{ .HASS_LONGITUDE }}"
        HASS_ELEVATION: "{{ .HASS_ELEVATION }}"
        HASS_LUTRON_USER: "{{ .HASS_LUTRON_USER }}"
        HASS_LUTRON_PASSWORD: "{{ .HASS_LUTRON_PASSWORD }}"
        HASS_TWILIO_ACCOUNT_SID: "{{ .HASS_TWILIO_ACCOUNT_SID }}"
        HASS_TWILIO_AUTH_TOKEN: "{{ .HASS_TWILIO_AUTH_TOKEN }}"
        HACS_GITHUB_TOKEN: "{{ .HACS_GITHUB_TOKEN }}"
        HASS_RECORDER_DB_URL: "postgresql://{{ .HASS_USER }}:{{ .HASS_USER_PASSWORD }}@postgres.database.svc.cluster.local:5432/{{ .HASS_DB }}"
  dataFrom:
    - extract:
        key: home-assistant
    - extract:
        key: postgres
