---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: home-assistant-secret
    template:
      data:
        HASS_LATITUDE: "{{ .HASS_LATITUDE }}"
        HASS_LONGITUDE: "{{ .HASS_LONGITUDE }}"
        HASS_ELEVATION: "{{ .HASS_ELEVATION }}"
        HASS_INFLUXDB_TOKEN: "{{ .ha_token }}"
        HASS_INFLUXDB_ORG: "{{ .ha_org }}"
        HASS_INFLUXDB_BUCKET: "{{ .ha_bucket }}"
        HASS_LUTRON_USER: "{{ .lutron_user }}"
        HASS_LUTRON_PASSWORD: "{{ .lutron_password }}"
        HASS_TWILIO_ACCOUNT_SID: "{{ .twilio_account_sid }}"
        HASS_TWILIO_AUTH_TOKEN: "{{ .twilio_auth_token }}"
  dataFrom:
    - extract:
        key: home-assistant
